{{- if .Values.schemaRegistry.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: {{ .Values.namespace.name }}
  labels:
    app: schema-registry
spec:
  replicas: {{ .Values.schemaRegistry.replicas }}
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
      - name: schema-registry
        image: "{{ .Values.schemaRegistry.image.repository }}:{{ .Values.schemaRegistry.image.tag }}"
        imagePullPolicy: {{ .Values.schemaRegistry.image.pullPolicy }}
        ports:
        - containerPort: 8081
        command:
        - /bin/bash
        - -c
        - |
          unset SCHEMA_REGISTRY_PORT
          /etc/confluent/docker/run
        env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: "schema-registry"
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: "{{ .Values.schemaRegistry.config.kafkastore.bootstrapServers }}"
        - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC
          value: "{{ .Values.schemaRegistry.config.kafkastore.topic }}"
        - name: SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL
          value: "{{ .Values.schemaRegistry.config.schemaCompatibilityLevel }}"
        - name: SCHEMA_REGISTRY_DEBUG
          value: "{{ .Values.schemaRegistry.config.debug }}"
        - name: SCHEMA_REGISTRY_LISTENERS
          value: "http://0.0.0.0:8081"
        - name: SCHEMA_REGISTRY_CUB_KAFKA_TIMEOUT
          value: "120"
        resources:
          {{- toYaml .Values.schemaRegistry.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 5
{{- end }}
