# =============================================================================
# Test-Probe Java Quickstart - Kubernetes Service
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-quickstart
  namespace: {{ .Values.namespace }}
  labels:
    app: java-quickstart
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: java-quickstart
    release: {{ .Release.Name }}
